typography_spectrum: 0.45930655381116686
content_rating:
  adult: false
color:
  lightness: 0.4793815243586271
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  saturation: 0.017019793169831137
  brandStrength: 0.7102204339149049
  rhythmicContrast: 0.9920840964095649
github: true
opengraph: {}
layout_spectrum: 0.8988561432975538
analytics: {}
author:
  name: akr4h
  url: 'http://www.ahr4h.com'
  email: akr4hn@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ecc3c8bb-a876-42f3-89fc-842975e76921.png
name: ^kr4h~
navigation:
  - name: instagram
    url: 'https://www.instagram.com/akr4hn/'
    type: external
  - name: youtube
    url: 'https://www.youtube.com/channel/UC0ihTMg1be1ZpdQHhjNtdig'
    type: external
  - name: soundcloud
    url: 'https://soundcloud.com/akr4hn'
    type: external
  - name: snapchat
    url: 'https://www.snapchat.com/add/akr4ah'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/87b7d6cf-dd9f-457a-93a5-81b9e5e61e67.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ^kr4h~
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a6d243e-0b7e-41f8-9f1e-61ff9bc2057d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a6d243e-0b7e-41f8-9f1e-61ff9bc2057d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/572721ff-c1b8-4385-bc87-ab5d2a301020.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/572721ff-c1b8-4385-bc87-ab5d2a301020.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/920b82a4-4bd5-4486-a843-ecb4bc5351ce.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/920b82a4-4bd5-4486-a843-ecb4bc5351ce.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/05c7573d-7585-4dcb-8b99-6172c7e76684.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/05c7573d-7585-4dcb-8b99-6172c7e76684.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ))) music (((
purpose:
  - type: contact
    url: 'mailto:akr4hn@gmail.com'
    label: contact
