typography_spectrum: 0.06860862409013628
color:
  saturation: 0.91460223748238
  brandStrength: 0.3825949521395977
  rhythmicContrast: 0.8337400713029068
  brandColors:
    - '#FEFEFE'
    - '#ABC0BE'
    - '#240827'
    - '#3B3068'
    - '#7287AA'
  lightness: 0.5063913229364201
github: true
layout_spectrum: 0.9445826211479482
author:
  url: 'http://www.ahr4h.com'
  name: akr4h
  email: akr4hn@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ecc3c8bb-a876-42f3-89fc-842975e76921.png
name: ^kr4h~
navigation:
  - name: soundcloud
    url: 'https://soundcloud.com/akr4hn'
    type: external
  - name: instagram
    url: 'https://www.instagram.com/akr4hn/'
    type: external
  - name: youtube
    url: 'https://www.youtube.com/channel/UC0ihTMg1be1ZpdQHhjNtdig'
    type: external
  - name: snapchat
    url: 'https://www.snapchat.com/add/akr4ah'
    type: external
  - name: DJ services
    id: fe949bee-12d4-4840-bbd1-80d77378434d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/87b7d6cf-dd9f-457a-93a5-81b9e5e61e67.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ^kr4h~
content: []
description: '#musicislife'
purpose:
  - type: contact
    url: 'mailto:akr4hn@gmail.com'
    label: contact
